### ISSUE TITLE
Don't we need to update triplea_maps.yaml for balanced mod

### ISSUE THREAD

**Issue by simon33-2** [triplea-maps/Project#36]
Hi,
Looks like the balanced mod has been included in the repository for 1.9 https://github.com/triplea-maps/world_war_ii_g40_balanced

Problem is that it isn't included in the triplea_maps.yaml file.

I'd be inclined to open a pull request for that myself but we I can't see where the map image would be hosted. I guess we could just reference the existing global one since it's undistinguishable.

Actually, can anyone see a problem with doing precisely that?

**Comment by simon33-2** [comment]
@DanVanAtta

**Comment by DanVanAtta** [comment]
No image URL is required. It's nice to have one in the description. TBD a more standardized location to store images / thumbnails.

Some options, store the image at the repository root folder. IE: note how each map repo has a "map" folder, only those contents are zipped. That means you can create additional folders/files in additions to "map". 

Another option, if you just want an image hosted, when opening an issue you can attach an image. Doing so generates a hosted URL for the image, which you can go on to use whether you submit the issue or not.

**Comment by simon33-2** [comment]
Thanks @DanVanAtta 

Here's the output from the window: 
triplea.engine.version.bin:1.9
Exception: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindow(DownloadMapsWindow.java:81)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindow(DownloadMapsWindow.java:72)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.lambda$layoutComponents$100(GameSelectorPanel.java:188)
	at games.strategy.ui.SwingComponents.lambda$newJButton$223(SwingComponents.java:164)
	at games.strategy.ui.SwingAction$2.actionPerformed(SwingAction.java:51)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


I've fixed the 1.2 vs 0.12 version bug but still getting these errors. I'll try removing all of the other maps and see if that fixes it.

**Comment by simon33-2** [comment]
Ok, I'm confused. I've tried putting back the r145 version of .yaml file and I'm still getting the same or similar errors.

**Comment by DanVanAtta** [comment]
That error means the game was not able to find the download list file (the .yaml) file.  Later tonight I'll see if I can improve it so it prints out the path to where it is expecting the file to be. You could try an absolute path in the game engine properties config, and double check that the file names match. You'll be shooting in the dark though until we can get some more debug info into that error message

**Comment by DanVanAtta** [comment]
"Ok, I'm confused. I've tried putting back the r145 version of .yaml file and I'm still getting the same or similar errors."

I'm assuming the "triplea_maps.yaml" file in the triplea installation home folder from a prerelease version.  The error posted indicates the game engine was unable to find the "triplea_maps.yaml" file entirely. Editing it will not alter the game engine behavior, since it can't find the file to begin with. An uncommenting of one line and commenting out of another in "game_engine.properties" should have made the local file get picked up, but we'll need a game engine update first to shed more light on what is happening  there, so please stand by.

@simon33-2  does that help clear up the confusion?

**Comment by simon33-2** [comment]
Yeah sorry, I figured it out. Was having trouble with dropbox not allowing me (in a way I could find) connecting to a file directly.

Sorted it by using a relative path on the local machine rather than an absolute one, believe it or not. Good enough for the purposes of testing.
